language: ruby
cache: bundler

rvm:
  - 2.0.0

env:
  - DB=postgresql

before_script:
  - psql -c 'create database net_network_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
